apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cars-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /rentals
            pathType: Prefix
            backend:
              service:
                name: rental-service
                port:
                  number: 4000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cars-service
                port:
                  number: 3000
