apiVersion: apps/v1
kind: Deployment
metadata:
  name: rental-deployment
  labels:
    app: rental-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rental-service
  template:
    metadata:
      labels:
        app: rental-service
    spec:
      containers:
        - name: rental-container
          image: hocinebour/rental-service:v5
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4000
          env:
            - name: PORT
              value: "4000"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "carrental"
            - name: DB_USER
              value: "carrental"
            - name: DB_PASSWORD
              value: "carrentalpass"
